In [1]:
# for is used to optimal Q : used for updation of Q value or q table 

In [2]:
#!pip install gymnasium
#!pip install gymnasium[toy-text]

In [3]:
import gymnasium as gym
import numpy as np 
import random

In [4]:
#Q table creation 
Q = np.zeros((48,4))

In [5]:
#we will Epsilson greedy policy 
gamma = 0.99
epsilon = 0.1
alpha = 0.5
episodes = 500

In [6]:
#to get state and predict next action, for updation q learning value is used Epsilon Policy 
def epsilon_greedy(state):
    if random.random() < epsilon:
        return env.action_space.sample() #explore

    else:
        return np.argmax(Q[state])

In [7]:
#q learning 

for episode in range(episodes):
    render = (episode % 100 == 0)

    if render :
        env = gym.make("CliffWalking-v1", render_mode = "human")

    else:
        env = gym.make("CliffWalking-v1")

    done = False
    state, _ = env.reset()

    episode_len = 0 
    tot_reward = 0

    #to start episode 
    while not done:
        action = epsilon_greedy(state)

        next_state, reward,terminated , truncated, _ = env.step(action)
        done = terminated or truncated 
        #Q learning update
        Q[state,action] += alpha  * (reward + gamma * np.max(Q[next_state]) - Q[state,action])
        state = next_state
        
        episode_len += 1
        tot_reward += reward 

    print(f"episodes  = {episode +1}/500 & Total Reward is{tot_reward} & episode len = {episode_len}")
    env.close()



episodes  = 1/500 & Total Reward is-759 & episode len = 264
episodes  = 2/500 & Total Reward is-1268 & episode len = 377
episodes  = 3/500 & Total Reward is-78 & episode len = 78
episodes  = 4/500 & Total Reward is-66 & episode len = 66
episodes  = 5/500 & Total Reward is-273 & episode len = 75
episodes  = 6/500 & Total Reward is-203 & episode len = 104
episodes  = 7/500 & Total Reward is-163 & episode len = 64
episodes  = 8/500 & Total Reward is-185 & episode len = 86
episodes  = 9/500 & Total Reward is-154 & episode len = 55
episodes  = 10/500 & Total Reward is-51 & episode len = 51
episodes  = 11/500 & Total Reward is-99 & episode len = 99
episodes  = 12/500 & Total Reward is-27 & episode len = 27
episodes  = 13/500 & Total Reward is-42 & episode len = 42
episodes  = 14/500 & Total Reward is-31 & episode len = 31
episodes  = 15/500 & Total Reward is-54 & episode len = 54
episodes  = 16/500 & Total Reward is-40 & episode len = 40
episodes  = 17/500 & Total Reward is-55 & episode len 

In [10]:
# What did the agent learn ?
env = gym.make("CliffWalking-v1", render_mode = "human")
state, _ = env.reset()
total_reward = 0
episode_len = 0 
done = False

while not done:
    action = np.argmax(Q[state])
    state, reward,terminated, truncated, _ = env.step(action) 
    done = terminated or truncated 

    episode_len += 1
    total_reward += reward 

print(f"total reward = {total_reward} & episode len = {episode_len}")
env.close()

#takes optimal shortest aggressive approach when compared to SARSA

total reward = -13 & episode len = 13


In [16]:
#tally Q value Q(s,a) state = 35 and 36
Q[36] #expected return in future through state value(action space in doc)
Q[35]



array([-2.96987425, -1.98902834, -1.        , -2.96970859])

In [17]:
Q[24]

array([-12.81290476, -11.36151283, -13.12500178, -12.24789657])

In [18]:
Q[29]

array([  -8.64697697,   -6.79346521, -112.11851228,   -8.64823019])